services:
  - type: web
    name: portfolio
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio.wsgi:application
    runtime: python-3.11.9
